/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DownloadFileServlet */

#ifndef _Included_DownloadFileServlet
#define _Included_DownloadFileServlet
#ifdef __cplusplus
extern "C" {
#endif
#undef DownloadFileServlet_serialVersionUID
#define DownloadFileServlet_serialVersionUID 1i64
#undef DownloadFileServlet_serialVersionUID
#define DownloadFileServlet_serialVersionUID 1i64
/*
 * Class:     DownloadFileServlet
 * Method:    export
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DownloadFileServlet_export
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
