/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Middle */

#ifndef _Included_Middle
#define _Included_Middle
#ifdef __cplusplus
extern "C" {
#endif
#undef Middle_serialVersionUID
#define Middle_serialVersionUID 1i64
#undef Middle_serialVersionUID
#define Middle_serialVersionUID 1i64
/*
 * Class:     Middle
 * Method:    importx
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Middle_importx
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
